// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWfuhVgvPqAKnSdDVdNWShX_CA6dfQvM',
    appId: '1:191121268682:web:e5174a742377af43c87933',
    messagingSenderId: '191121268682',
    projectId: 'seven-taxis',
    authDomain: 'seven-taxis.firebaseapp.com',
    storageBucket: 'seven-taxis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxZ3PWQVUaP-SghDXyNljXbPcBh-vvmo',
    appId: '1:191121268682:android:a064f03f4df5e806c87933',
    messagingSenderId: '191121268682',
    projectId: 'seven-taxis',
    storageBucket: 'seven-taxis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDRGyScsRFHDdyrGHGeR13SDdm-K5XB4',
    appId: '1:191121268682:ios:30cf795535d54145c87933',
    messagingSenderId: '191121268682',
    projectId: 'seven-taxis',
    storageBucket: 'seven-taxis.appspot.com',
    iosBundleId: 'com.seven.sevenTaxisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDRGyScsRFHDdyrGHGeR13SDdm-K5XB4',
    appId: '1:191121268682:ios:30cf795535d54145c87933',
    messagingSenderId: '191121268682',
    projectId: 'seven-taxis',
    storageBucket: 'seven-taxis.appspot.com',
    iosBundleId: 'com.seven.sevenTaxisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWfuhVgvPqAKnSdDVdNWShX_CA6dfQvM',
    appId: '1:191121268682:web:4f5e0cb628f12a5bc87933',
    messagingSenderId: '191121268682',
    projectId: 'seven-taxis',
    authDomain: 'seven-taxis.firebaseapp.com',
    storageBucket: 'seven-taxis.appspot.com',
  );
}
